apiVersion: apps/v1
kind: Deployment
metadata:
  name: bison-deployment
spec:
  replicas: 1  # Number of instances (pods) to run
  selector:
    matchLabels:
      app: bison-dep
# everything under template is the definition of the pod that will be created.      
  template:
    metadata:
      labels:
        app: bison-app
    spec:
      containers:
      - name: bison-con
        image: waldbaan/bison:latest
        ports:
        - containerPort: 80


